### ISSUE TITLE
系统安装都是正常，但是登录老是不成功

### ISSUE THREAD

**Issue by yanliang941225** [gopeak/masterlab#103]
passport/do_login 已经返回{"ret":"200","msg":"\u4eb2,\u767b\u5f55\u6210\u529f","data":{"user":{"uid":"1","directory_id":"1","phone":"18002510000","username":"master","openid":"q7a752741f667201b54780c926faec4e","status":"1","first_name":"","last_name":"master","display_name":"Master","email":"master@masterlab.vip","sex":"1","birthday":"","create_time":"0","update_time":"0","avatar":"http:\/\/10.180.120.22\/gitlab\/images\/default_user.png","source":"","ios_token":null,"android_token":null,"version":null,"token":null,"last_login_time":"1547459990","is_system":"0","login_counter":"0","title":"\u7ba1\u7406\u5458","sign":"\u4ea4\u4ed8\u5353\u8d8a\u4ea7\u54c1!","k":"1","create_time_text":""},"msg":"\u4eb2,\u767b\u5f55\u6210\u529f","code":1,"token":"f9ffcb4ed6b8c8a2a33a422e123c407c1d5207245858fce5962b6df0950015e4","refresh_token":"d57c488cf65de35e889e6c9ae10ba3055b3eb0f3d2246b922f5b1a7759aa70a4","token_expire":2592000}}   上面已经表示登录成功了，但是 window.location.href = 'http://10.180.120.22/'时候登录验证失败，有重定向了！

**Comment by weichaoduo** [comment]
该问题已经在官方网站的文档中提到解决方法: http://www.masterlab.vip/help.php?md=faq ，是因为php的session目录无法写入问题引起的。
具体解决方法:
1. 访问 /install/?step=1 ,检查环境配置是否正确
2. 访问 /p.php  查找 session.save_path 值
3. 赋予当前运行的php用户拥有可写入权限， 举例赋予权限命令
`chown -R apache:apache /var/lib/php/session`
