### ISSUE TITLE
系统存在极其严重的安全漏洞

### ISSUE THREAD

**Issue by caiweiming** [gopeak/masterlab#118]
不可否认，贵公司的这个系统确实很不错，无论是用户体验还是操作流程都非常不错，也很符合我们的需求。
但是系统在安全性还是非常欠缺，除了我之前提到的可以删除master账号外，今天还发现了一个更为严重的安全漏洞。
可以在不需要登录后台的情况下，直接访问admin模块下的任何页面，比如以下页面：
http://域名/admin/project
http://域名/admin/issue_type
http://域名/admin/user
http://域名/admin/system
等于整个系统的管理权限都可以使用了，希望官方能尽早修复，也系统能在安全性上更加完善。
虽然可以把系统部署到公司内网，但这样的漏洞还是不应该存在。
最后，感谢贵公司提供了这么好的产品，希望未来越来越强大。

**Comment by lyman-server** [comment]
感谢提供反馈，我们会尽快修复已知的bug

**Comment by weichaoduo** [comment]
已经更新补丁修复漏洞：
https://github.com/gopeak/masterlab/releases/download/v1.0.4/upgrade-patch-v1.0.3tov1.0.4.zip
