### ISSUE TITLE
权限控制功能完善

### ISSUE THREAD

**Issue by fsconline** [gopeak/masterlab#128]
权限做好是基于角色去控制。或者基于组织也需要为组织内添加人员。
最基本关系可以为：事项归属项目、项目归属组织、组织已分配人员可直接查看当前组内项目
更细化的：为组内的项目添加人员。
我觉得人员权限可以参考下 Mantis Bug Tracker  能满足日常项目使用要求

**Comment by weichaoduo** [comment]
我们会下一次大版本v2.0中完善权限功能，目前的权限设计是： 

- 系统管理员
-  项目基于角色控制

的权限方案
