### ISSUE TITLE
在增加事项描述的时候能否支持剪切板截图

### ISSUE THREAD

**Issue by yangqingming** [gopeak/masterlab#130]
在增加事项描述的时候能否支持剪切板截图?
![image](https://user-images.githubusercontent.com/10525350/58884680-70e9a700-8713-11e9-9fa4-e31122cc4e12.png)

**Comment by juggwalker** [comment]
在1.2版本中已经支持截图粘贴功能了，1.2版本近期发布

**Comment by yangqingming** [comment]
6666
