### ISSUE TITLE
多个收件人发送邮件失败

### ISSUE THREAD

**Issue by langsz** [gopeak/masterlab#133]
打开管理->系统->邮箱设置，配置完后，点击发送测试，收件人填写两个以上邮箱并;分隔。
返回邮件发送失败：<strong>Invalid address:  (addAnAddress to):

**Comment by langsz** [comment]
在app/classes/Systemlogic.php文件中的directMail函数中应加上如下代码：
if (is_string($recipients)) {
            $recipients = explode(';', $recipients);
        }
        if (empty($replyTo)) {
            $replyTo = [];
        }
        if (is_string($replyTo)) {
            $replyTo = explode(';', $replyTo);
        }

**Comment by weichaoduo** [comment]
是这样的

**Comment by weichaoduo** [comment]
1.1.1版本发布时修复此bug

**Comment by langsz** [comment]
异步发邮件报错：501 5.1.7 Invalid address。我下载安装的的是1.1版本。

**Comment by weichaoduo** [comment]
首先确保：邮件配置正确，其次masterlab_socket正常运行，报错 Invalid address 表明传递给masterlab_socket的邮箱地址格式错误或地址不存在

**Comment by langsz** [comment]
邮件配置中，经过发送邮件测试，是可以的发送邮件的，说明直接发邮件是可以的。异步发邮件，不管是收件人是一个还是多个，都显示这个错误。masterlab_socket已经在运行。

**Comment by langsz** [comment]
异步发邮件的路径是否放在masterlab_socket中？是否这部分的解析有问题？

**Comment by weichaoduo** [comment]
Invalid address 是发给邮件服务器的实际返回错误提示，这个问题你加下QQ群314155057让群主给你调试解决

**Comment by langsz** [comment]
问题找到了，是masterlab_socket程序问题。在这个源码使用的是stmp模块，woker/mail.go文件的sendByNoSSL函数中，msg变量的From和sendMail中的from参数应该使用mailContent.From，而不应使用mailContent.User
