### ISSUE TITLE
邮箱通知配置不成功

### ISSUE THREAD

**Issue by langsz** [gopeak/masterlab#145]
进入：管理->系统->邮箱通知配置
点击：修改，弹出修改窗口。
1、页面的多个元素使用同一个id属性值；
2、form提交后数据不包含未选择的user, 例如事项评论所有选项不选中，form data中不包含这项数据，导致无法更新事项评论的对应的数据。

**Comment by juggwalker** [comment]
是在哪个版本下出现的问题？
v1.2以下的版本会出现这个问题，v1.2中已经修复了该bug
![image](https://user-images.githubusercontent.com/41332880/61058282-7d0b0780-a429-11e9-8a41-5fe6a01c5b85.png)

**Comment by langsz** [comment]
1.1版本

**Comment by langsz** [comment]
> 是在哪个版本下出现的问题？
> v1.2以下的版本会出现这个问题，v1.2中已经修复了该bug
> ![image](https://user-images.githubusercontent.com/41332880/61058282-7d0b0780-a429-11e9-8a41-5fe6a01c5b85.png)
