### ISSUE TITLE
头像上传不显示的问题

### ISSUE THREAD

**Issue by qdhonker** [gopeak/masterlab#150]
在centos7上安装了masterlab后，用户的头像上传能成功，但是头像不能正常显示
头像保存路径：app/storage/attachment/avatar
浏览显示头像路径：xxx.com/attachment/avatar/1.png?t=1564220283

**Comment by weichaoduo** [comment]
程序没有问题的，你需要在nginx中，进行别名设置。
http://www.masterlab.vip/help.php?md=install-linux
举例如下：
location ^~ /attachment/ {
        root  /data/www/masterlab/app/storage/;
    }

**Comment by weichaoduo** [comment]
v2.0已解决

**Comment by lemonwuhao** [comment]
我现在是2.1.3也存在这个问题，怎么解决？

**Comment by weichaoduo** [comment]
> 我现在是2.1.3也存在这个问题，怎么解决？

加群 314155057 联系群主 或者加QQ 121642038 ，远程协助解决
