### ISSUE TITLE
nginx下可以部署到子目录下吗？

### ISSUE THREAD

**Issue by weituotian** [gopeak/masterlab#159]
**功能描述**
因为nginx的根目录已经部署了其它的系统了，所以可以在子目录下部署masterlab吗？

**功能点**
1. 子目录部署

**规则和影响**
1. 子目录部署
2. xxx

**解决方案**
nginx应该怎么配置，masterlab的程序代码是否需要修改?

**Comment by weichaoduo** [comment]
1.2版本之后已经不支持 诸如 http://www.xxxx.com/masterlab 访问了。
Nasterlab的代码文件可以放在任意目录中，建议在nginx中设置不同的端口来访问，比如：
http://www.xxxx.com:8888/

**Comment by weituotian** [comment]
@weichaoduo 谢谢回答，明白了
