### ISSUE TITLE
点击bug解决结果选项，提示表单验证失败

### ISSUE THREAD

**Issue by xiuchanghu** [gopeak/masterlab#167]
点击bug解决结果选项，提示表单验证失败

**重现步骤**
1. 点击迭代下某个bug
2. 点击解决结果，选择已解决或其它选项
3. 提示表单验证失败
4. 查看开发者工具ajax返回
priority: "优先级不能为空"
assignee: "经办人不能为空"
5。但是这两项不是空的

**期望结果**
正常处理

**实际结果**
处理异常

**Comment by weichaoduo** [comment]
已经在修复中,本周内发布版本解决
