### ISSUE TITLE
启动服务用的masterlab_socket在哪里？没找到呀

### ISSUE THREAD

**Issue by littleheary** [gopeak/masterlab#170]
我搜索了全部目录，都没找到这个文件，那岂不是没办法运行起来？

**Comment by colder-winter** [comment]
https://github.com/gopeak/masterlab_socket/releases
这里下载，可能需要梯子

**Comment by colder-winter** [comment]
> 我搜索了全部目录，都没找到这个文件，那岂不是没办法运行起来？

https://github.com/gopeak/masterlab_socket/releases
这里下载，可能需要梯子

**Comment by weichaoduo** [comment]
已经改用swoole服务,执行命令
cd ./bin
php ./swoole_server.php
