### ISSUE TITLE
按照官方教程搭建完毕以后，打不开install，一直提示file not found

### ISSUE THREAD

**Issue by littleheary** [gopeak/masterlab#171]
nginx的配置文件，在`fastcgi_param  SCRIPT_FILENAME  /data/www/masterlab/app/public$fastcgi_script_name;`这里，我已经试过了写路径和环境变量，都不行。
我也把nginx和php-fpm的运行用户都改为同一个用户nginx，还是不行
我把masterlab的根目录设置为nginx用户所属，权限777，还是不行。

请问，这到底是啥问题？

**Comment by unhumanplane** [comment]
你好，我也碰到了这个问题，请问你是怎么解决的
