### ISSUE TITLE
安装完毕以后，进入登录页面，输入用户名和密码，跳转进入一个空白的页面，状态码是500

### ISSUE THREAD

**Issue by littleheary** [gopeak/masterlab#172]
安装完毕以后，进入登录页面，输入用户名和密码，进入空白页面，状态码是500，这是因为我差了点啥么、

**Comment by weichaoduo** [comment]
请把你的环境说一下：
操作系统，web服务器(Apache还是nginx),通过哪个教程安装的？ 
如果是从master分支clone的话，是需要 composer 安装类库的；  
查看具体错误，请修改 `app/config/deploy/app.cfg.php` 代码第一行  
`error_reporting(E_ERROR);` 修改为  
`error_reporting(E_ALL);`

**Comment by littleheary** [comment]
web服务器是centos7、nginx、php7、mysql57、redis；
安装方法是使用http://www.masterlab.vip/help.php?md=install-linux这个的安装方法；
代码是通过wget -c http://www.masterlab.vip/download.php?file=masterlab-full-last.zip  -O masterlab.zip这样下载的；
```
app/config/deploy/app.cfg.php 代码第一行
error_reporting(E_ERROR); 修改为
error_reporting(E_ALL);
```
这里我已经改过了，页面还是空白，返回状态吗依然是500
![image](https://user-images.githubusercontent.com/26987382/74578470-d0e95a80-4fcf-11ea-8428-10bf7b8d01cc.png)

**Comment by littleheary** [comment]
具体的报错内容如下
2020/02/15 09:13:45 [error] 16353#0: *8 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught PDOException: SQLSTATE[42S22]: Column not found: 1054 Unknown column 'archived' in 'where clause'
[{"file":"\/data\/www\/masterlab\/lib\/MyPdo.php","line":196,"function":"execute","class":"PDOStatement","type":"-\u003E","args":[]},{"file":"\/data\/www\/masterlab\/lib\/MyPdo.php","line":149,"function":"exec","class":"main\\lib\\MyPdo","type":"-\u003E","args":["SELECT  id as k,`project_main`.* FROM `project_main`   WHERE `archived` = :archived    ORDER BY id    asc   ",{":archived":"N"}]},{"file":"\/data\/www\/masterlab\/lib\/MyPdo.php","line":273,"function":"query","class":"main\\lib\\MyPdo","type":"-\u003E","args":["SELECT  id as k,`project_main`.* FROM `project_main`   WHERE `archived` = :archived    ORDER BY id    asc   ",{":archived":"N"}]},{"file":"\/data\/www\/masterlab\/app\/model\/DbModel.php","line":351,"function":"getRows","class":"main\\lib\\MyPdo","type":"-\u003E","args":["SELECT  id as k,`project_main`.* FROM `project_main`   WHERE `archived` = :archived" while reading response header from upstream, client: 192.168.217.1, server: www.ccspm.ccs, request: "GET / HTTP/1.1", upstream: "fastcgi://127.0.0.1:9000", host: "www.ccspm.ccs:8081", referrer: "http://www.ccspm.ccs:8081/passport/login"

**Comment by weichaoduo** [comment]
感谢你的报告的bug，现在已经修复了，是因为代码合并dev的问题。
麻烦你再下载代码安装下。

**Comment by weichaoduo** [comment]
已经解决
