### ISSUE TITLE
管理模块报错

### ISSUE THREAD

**Issue by BossDing** [gopeak/masterlab#178]
`php
Fatal error: Uncaught Exception: main\app\ctrl\SettingsModule class no found; in /www/wwwroot/masterlab/vendor/hornet/framework/src/framework/HornetEngine.php:603 Stack trace: #0 /www/wwwroot/masterlab/vendor/hornet/framework/src/framework/HornetEngine.php(417): framework\HornetEngine->routeCtrl() #1 /www/wwwroot/masterlab/app/public/index.php(37): framework\HornetEngine->route() #2 {main} thrown in /www/wwwroot/masterlab/vendor/hornet/framework/src/framework/HornetEngine.php on line 603
`

**Comment by weichaoduo** [comment]
下载最新的v2.1版本重新安装。
