### ISSUE TITLE
安装完毕后首页500

### ISSUE THREAD

**Issue by ld0574** [gopeak/masterlab#179]
2.0版本，全新安装，尝试过composer update，问题依旧，报错日志为：
`PHP Fatal error:  Uncaught Exception: main\\app\\ctrl\\Php class  no found; in /data/wwwroot/masterlab/vendor/hornet/framework/src/framework/HornetEngine.php:603
Stack trace:
#0 /data/wwwroot/masterlab/vendor/hornet/framework/src/framework/HornetEngine.php(417): framework\\HornetEngine->routeCtrl()
#1 /data/wwwroot/masterlab/app/public/index.php(37): framework\\HornetEngine->route()
#2 {main}
  thrown in /data/wwwroot/masterlab/vendor/hornet/framework/src/framework/HornetEngine.php on line 603`

**Comment by speedecho** [comment]
3.0同样遇到这种问题
