### ISSUE TITLE
支持OpenLDAP账户登录

### ISSUE THREAD

**Issue by Rongcong** [gopeak/masterlab#185]
**功能描述**
作为公司配置管理工程师，我希望能够将这么好用的基于事项驱动和敏捷开发的项目管理工具Masterlab带给同事们使用。因为我们公司采用LDAP来统一管理大家内部网站的账户，所以希望Masterlab也能够提供接口，支持OpenLDAP账户管理。

**功能点**
1. 实现OpenLDAP用户登录

**规则和影响**
1. 能够读取OpenLDAP用户信息，使得OpenLDAP用户能够直接登录Masterlab账户。

**Comment by weichaoduo** [comment]
感谢您的支持，预计规划下个大版本3.0（2个月内）实现该功能。






------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Rongcong Xu"<notifications@github.com&gt;;
发送时间:&nbsp;2020年3月2日(星期一) 晚上8:16
收件人:&nbsp;"gopeak/masterlab"<masterlab@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[gopeak/masterlab] 支持OpenLDAP账户登录 (#185)




功能描述
 作为公司配置管理工程师，我希望能够将这么好用的基于事项驱动和敏捷开发的项目管理工具Masterlab带给同事们使用。因为我们公司采用LDAP来统一管理大家内部网站的账户，所以希望Masterlab也能够提供接口，支持OpenLDAP账户管理。
 
功能点
  
实现OpenLDAP用户登录
  
规则和影响
  
能够读取OpenLDAP用户信息，使得OpenLDAP用户能够直接登录Masterlab账户。

**Comment by weichaoduo** [comment]
更新下。
此bug，将在近日发布的v2.1版本中解决。
