### ISSUE TITLE
2.0.2修改状态操作失败

### ISSUE THREAD

**Issue by RouGang** [gopeak/masterlab#198]
这里输入对bug做出清晰简洁的描述.

**重现步骤**
1. 修改状态为已关闭
![image](https://user-images.githubusercontent.com/5804672/76934637-76bf1a80-692a-11ea-996b-179a51fbc0cf.png)

2. 弹出错误
![image](https://user-images.githubusercontent.com/5804672/76934667-83437300-692a-11ea-8e58-98954f056d3c.png)

3. xxxx
4. xxxxxx

**期望结果**
期望修改状态成功

**实际结果**
简述实际看到的结果，这里可以配上截图
![image](https://user-images.githubusercontent.com/5804672/76934676-89395400-692a-11ea-9388-94b755c203e5.png)

**附加说明**
附加或额外的信息

**Comment by weichaoduo** [comment]
此bug，将在近日发布的v2.1版本中解决。
