### ISSUE TITLE
在线升级不起作用

### ISSUE THREAD

**Issue by RouGang** [gopeak/masterlab#205]
这里输入对bug做出清晰简洁的描述.

**重现步骤**
1. 未检查到最新版本2.1

![image](https://user-images.githubusercontent.com/5804672/77729290-41f14880-7039-11ea-91d4-955696e73b52.png)

2. xxx
3. xxxx
4. xxxxxx

**期望结果**
希望能升级到2.1

**实际结果**
简述实际看到的结果，这里可以配上截图

**附加说明**
附加或额外的信息

**Comment by weichaoduo** [comment]
如果是 2.0 或 2.0.1 版本，暂时未支持在线升级。需要手动升级。
详看文档
http://www.masterlab.vip/help.php?md=upgrade
http://www.masterlab.vip/help.php?md=faq#%E5%8D%87%E7%BA%A7%E5%A4%B1%E8%B4%A5%E6%80%8E%E4%B9%88%E8%A7%A3%E5%86%B3%EF%BC%9F

**Comment by weichaoduo** [comment]
如果升级失败，编辑 app/config/deploy/app.cfg.php文件，将MASTERLAB_VERSION
修改为原版本号，然后重新进入升级界面再次升级。如果无法得到解决，请加群联系群主。
