### ISSUE TITLE
主页URL错误，部分页面URL拼接错误

### ISSUE THREAD

**Issue by rorschach-py** [gopeak/masterlab#211]
主页URL显示为   ://localhost:81/

部分URL错误拼接如下：
http://127.0.0.1:81/admin/://localhost:81/admin/system
http://127.0.0.1:81/://localhost:81/attachment/project/avatar/2.png

在 masterlab\app\config\deploy\app.cfg.php 中手动配置静态地址可以解决，不过不太方便

**Comment by weichaoduo** [comment]
您提出的bug，新版本无法重现，可能旧版本遗留的问题。
![image](https://user-images.githubusercontent.com/6365163/77990695-93107d80-7354-11ea-8845-4c20737e4e91.png)
