### ISSUE TITLE
nginx调整增加项目名的配置

### ISSUE THREAD

**Issue by twonm** [gopeak/masterlab#215]
masterlab无法没有项目目录  只能放置在nginx

**Comment by twonm** [comment]
实际使用过程中nginx的一个80端口需要配置好几个项目通过if ($request_uri ~ "^\/masterlab\/"){}来区分 想知道怎么增加这个 访问的时候入口从http://域名/  修改未http://域名/ 自定义名称/

**Comment by weichaoduo** [comment]
为了简化安装过程，masterlab从v1.2版本后移除了对
http://域名/ 自定义名称/
支持的支持

后续版本，视情况加入该功能

**Comment by twonm** [comment]
若我现在想在我的版本里面加入这种配置有什么办法吗？请指导一下
