### ISSUE TITLE
搜索事项是否可以针对字段【描述】进行关键字模糊搜索

### ISSUE THREAD

**Issue by fufp** [gopeak/masterlab#227]
根据目前的demo，在查询事项的高级查询条件中，有很多字段，比如状态、标题等，可以根据这些字段结合查询条件组合成不同的过滤器并保存下来。这个功能非常实用。
但好像这个功能中的字段是固定的，没有我比较关注的【描述】这个字段。有时提的一些需求或者问题太多了，想不起是哪个了，想通过一些关键字去模糊搜索【描述】字段进而找到这个需求。
但高级查询字段里没有这个字段，是否可以增加这个字段？或者是高级查询的字段能否也可以自定义？
谢谢！

**Comment by weichaoduo** [comment]
此功能已经列入 3.0 的待办事项列表。

**Comment by weichaoduo** [comment]
v2.1.6 fixed
