### ISSUE TITLE
支持多个迭代同时进行中

### ISSUE THREAD

**Issue by allenorac** [gopeak/masterlab#229]
**功能描述**
实际项目操作中会有多个功能迭代同时进行，目前只能有1个迭代进行中，其他迭代的任务无法修改状态。

**功能点**
1. 项目创建多个迭代，迭代实际开始时自动进入进行中状态
2. 同时可以有多个迭代进行中

**附加内容**
版本2.1.1

**Comment by weichaoduo** [comment]
此功能已经列入 3.0 的待办事项列表。

**Comment by ZaXk** [comment]
非常赞同
