### ISSUE TITLE
附件文件不能下载

### ISSUE THREAD

**Issue by allenorac** [gopeak/masterlab#231]
附件中上传txt文本文件，或jpg图片。查看任务的页面中无法下载该附件。

**重现步骤**

![image](https://user-images.githubusercontent.com/12723796/79856116-7b319400-83fe-11ea-9a1a-f7f47371876e.png)

**期望结果**
可以正常下载文本附件
可以正常预览和下载图片文件

**实际结果**
无法下载

**附加说明**
版本2.1.1

**Comment by weichaoduo** [comment]
管理员身份进入“管理/系统设置/附件设置”
确定“附件路径”为：{{PUBLIC_PATH}}attachment
同时要赋予php用户  masterlab/app/public/attachment 及子目录读写权限

**Comment by allenorac** [comment]
请问附件如何下载, 没有下载按钮.
系统权限和目录读写权限已经检查过了没问题.
