### ISSUE TITLE
LDAP配置好以后，用LDAP登录，提示“该用户尚未激活”

### ISSUE THREAD

**Issue by zhulei007** [gopeak/masterlab#235]
这里输入对bug做出清晰简洁的描述.

**重现步骤**
1. xx
2. xxx
3. xxxx
4. xxxxxx

**期望结果**
简洁清晰的描述期望结果

**实际结果**
简述实际看到的结果，这里可以配上截图

**附加说明**
附加或额外的信息

**Comment by hieastz** [comment]
可以换一个用户登录试试，你可能把master的邮箱设置成你的邮箱了，换其他人登录试试。

**Comment by weichaoduo** [comment]
管理员账号登录， 在  “管理/用户管理”审核通过此用户
