### ISSUE TITLE
安装Masterlab时第三步，MySQL连接不上

### ISSUE THREAD

**Issue by Eugene-Zhou** [gopeak/masterlab#236]
依照官方Windows安装Masterlab教程，前2步一切顺利。
卡在第三步显示“MySQL连接失败，请检查连接配置”。
为了检查MySQL是否正确，使用了NaviCat和Windows的ODBC，均可以成功连接MySQL。
![issue-masterlab](https://user-images.githubusercontent.com/64573705/80674428-67fc8380-8ae4-11ea-96b0-a89494f00573.png)

**Comment by weichaoduo** [comment]
如果使用 docker 方式进行安装，可能存在此问题。
请使用非docker方式安装：
http://www.masterlab.vip/help.php?md=install-linux

如还未解决，请加QQ群314155057 联系群主
