### ISSUE TITLE
提供一个重新发送激活邮件的按钮

### ISSUE THREAD

**Issue by jiangming1399** [gopeak/masterlab#241]
**功能描述**
当前新注册的用户若无法收到激活邮件，因没有办法重新发送激活邮件，故此用户将永远无法激活。

**解决方案**
提供一个重新发送激活邮件的按钮。

**备用方案**
通过邮件重置密码后，将此用户视为已经激活。

**Comment by weichaoduo** [comment]
当邮件系统不可用时，可使用管理员账号登录。
在“管理”/"用户管理"页面手动激活该用户。

**Comment by jiangming1399** [comment]
虽然是可以使用管理员账号手动激活，但个人认为还是能提供一个重发按钮为好。

**Comment by weichaoduo** [comment]
后天升级2.1.4版本可解决

**Comment by weichaoduo** [comment]
v2.1.5版本已解决
