### ISSUE TITLE
项目人员名单的链接错误

### ISSUE THREAD

**Issue by jiangming1399** [gopeak/masterlab#246]
这里的链接是`https://***/user/profile/ 12214`，多了一个空格。同时通过这个链接访问居然能看到东西，而不是显示404

**重现步骤**
1. 访问项目人员页面 settings_project_member
2. 随意点击一个人，查看profile

**期望结果**
进入正确profile页面

**实际结果**
进入了错误的profile页面

**Comment by weichaoduo** [comment]
v2.1.5版本已解决

**Comment by jiangming1399** [comment]
@weichaoduo 链接中带空格能访问的问题还没解决
