### ISSUE TITLE
事项表格视图的协助人不显示内容

### ISSUE THREAD

**Issue by smn568** [gopeak/masterlab#249]
这里输入对bug做出清晰简洁的描述.

事项列表中以表格视图浏览事项内容，发现“协助人”这一列的内容都是空白。

**重现步骤**
1. 进入项目
2. 点击“事项”
3. 选择“表格视图”
4. 必现

**期望结果**
像“经办人“贺”报告人“一样显示”协助人“

**Comment by weichaoduo** [comment]
默认情况下，协助人字段不显示，要显示，则通过一下操作设置即可：
![图片](https://user-images.githubusercontent.com/6365163/146155534-eadbdfe1-98e6-4389-8cb8-274acaf6f7f3.png)
![图片](https://user-images.githubusercontent.com/6365163/146155572-44be5755-6772-4fb3-a922-3a89fe659ae1.png)
