### ISSUE TITLE
记住登录状态下，还是会提示会话过期

### ISSUE THREAD

**Issue by jiangming1399** [gopeak/masterlab#253]
记住登录状态下，还是会提示会话过期。点击重新登录按钮并不会导向登录框，而是直接以登录状态进入主页

**重现步骤**
1. 登录，选择记住账户
2. 进入随便一个页面，等待
3. 会话过期后，点击链接，会提示会话过期
4. 点击重新登录按钮，直接登录进入主页

**期望结果**
不出现会话过期窗口

**Comment by weichaoduo** [comment]
v2.1.6已修复此bug
注：
"记住账号"是注销后，无需输入账号面，可以直接点击按钮登录；
而要保持会话一直不过期，则需要修改  app/config/session.cfg.php 的  `session.cookie_lifetime` 的值
