### ISSUE TITLE
多域名指向同一站点时无法正常登录

### ISSUE THREAD

**Issue by jim-kirisame** [gopeak/masterlab#258]
我有一个站点，拥有两个不同的域名。其中一个域名可以正常使用，但是另一个域名无法正常登录。

**重现步骤**
1. 访问登录页面
2. 输入账号密码登录
3. 发现返回的Cookie域名不正确，导致无法正常登录

**Comment by weichaoduo** [comment]
确实存在争议的问题，因为cookie使用了泛域名。后续将取消泛域名

**Comment by weichaoduo** [comment]
确实存在这样的问题，因为cookie使用了泛域名。后续将取消泛域名
