### ISSUE TITLE
在一个项目中使用过滤器时点击分页过滤范围会变成所有项目

### ISSUE THREAD

**Issue by ausmas** [gopeak/masterlab#263]
这里输入对bug做出清晰简洁的描述.

**重现步骤**
1. 进入一个项目
2. 使用过滤器
3. 点击分页中的2、3、……
4. 查看结果

**期望结果**
过滤器过滤范围正常

**实际结果**
点击分页后过滤范围从当前项目变成所有项目

**附加说明**
版本2.1.9

**Comment by weichaoduo** [comment]
3.0中已经修复此bug，近期将提供2.1至3.0的升级脚本
