### ISSUE TITLE
导入事项后报告人无法显示

### ISSUE THREAD

**Issue by ausmas** [gopeak/masterlab#264]
这里输入对bug做出清晰简洁的描述.

**重现步骤**
1. 在模板中给填写事项信息包括经办人、报告人
2. 导入
3. 查看报告人

**期望结果**
报告人正常显示

**实际结果**
报告人为空

**附加说明**
2.1.9

**Comment by weichaoduo** [comment]
报告人一列请输入用户名，目前在2.1.10和3.0版本未能重现此bug
