### ISSUE TITLE
代码整合、持续集成、测试用例管理、wiki文档管理

### ISSUE THREAD

**Issue by xianyo** [gopeak/masterlab#266]
项目非常好，希望能在官网上面提供下后续版本的功能开发线路图！未来可期。

一些建议：

代码整合：
我觉得phabricator的代码整合比较好，可以参考一下。
项目关联git repo，
当发起代码评审单的时候，自动变成一个事项，
当一个commit提交后，可以关联某一事项（需求，bug等）

持续集成：
迭代能够和持续集成整合，比如关联jenkins。
每次迭代能够通过关联的事项生成changlog

测试用例管理：
提供测试用例管理，能够关联事项中的测试bug。

wiki文档管理：
支持markdown

**Comment by weichaoduo** [comment]
目前先把3.0的版本稳定了，下一期 技术架构全面升级，您提出的开发路线图将会纳入
