### ISSUE TITLE
邮件不发送

### ISSUE THREAD

**Issue by luorenjin** [gopeak/masterlab#268]
见附件
![image](https://user-images.githubusercontent.com/7892385/91169764-75302480-e70a-11ea-9b9e-ce308f9a7275.png)

**Comment by hieastz** [comment]
附件看不见呢，如果登录的邮箱账号是不带@xx.com，当前的版本是会失败的，因为异步发送的时候没有取from，而是取的user。
可以自行下载masterlab_socket 搜索mail.go,95行改为mailContent.From

**Comment by weichaoduo** [comment]
邮件发送发布已经变更为swoole,执行命令：
```
cd  ./bin 
php ./swoole_server.php

```
