### ISSUE TITLE
文档管理页打不开

### ISSUE THREAD

**Issue by sangjiexun** [gopeak/masterlab#284]
![微信截图_20201125163446](https://user-images.githubusercontent.com/59449516/100202412-3c3b6200-2f3c-11eb-863f-340f70cdcd22.png)
![微信截图_20201125163123](https://user-images.githubusercontent.com/59449516/100202416-3e9dbc00-2f3c-11eb-9cc0-0b6fa6707ecd.png)

如图所示。我感觉是“\/”处有问题，请问如何修正
页面回传信息如下：
{ "code": true, "use_time": 0.43355512619018555, "data": "0aa0VWlLpvChtLJZUMXRdSP0LVzOY50xNHBi4Huo2qbg-z3dsMbMhJiKBYIOIZO7b4t9nPHHVA", "REQUEST_URI": "\/kod_index.php?user\/loginSubmit&isAjax=1&getToken=1&login_token=YWRtaW4=%7C83ca7512188b3070a1cd9b4977bc17dc" }{ "code": true, "use_time": 0.43549203872680664, "data": "0ba1AkC-v4N__zcgBgnWShUEaA8xN7kXVN4G0CK4ityB9G9TrxySaXwSDhH0aL00E-QTTihZXA", "REQUEST_URI": "\/kod_index.php?user\/loginSubmit&isAjax=1&getToken=1&login_token=YWRtaW4=%7C83ca7512188b3070a1cd9b4977bc17dc" }{ "code": true, "use_time": 0.4400448799133301, "data": "10afF0qvytYcn-ZN95CKdpSorhe4KrPVeaMPWTIknVBXRl6PTMuoAA8mFWH_SJTf3BPnQlZacA", "REQUEST_URI": "\/kod_index.php?user\/loginSubmit&isAjax=1&getToken=1&login_token=YWRtaW4=%7C83ca7512188b3070a1cd9b4977bc17dc" }

**Comment by weichaoduo** [comment]
请尝试给   plugin/document 及子目录赋予权限

**Comment by CODEJAS0N** [comment]
尝试您说的方法没有效果
#284

**Comment by CODEJAS0N** [comment]
> 请尝试给 plugin/document 及子目录赋予权限

![微信截图_20201126081609](https://user-images.githubusercontent.com/59449516/100294034-91b95280-2fc0-11eb-8f83-5ace144c5e89.png)
![微信截图_20201126082130](https://user-images.githubusercontent.com/59449516/100294036-93831600-2fc0-11eb-8fb9-a9818251a5e3.png)
具体请见截图

**Comment by CODEJAS0N** [comment]
有劳了

**Comment by CODEJAS0N** [comment]
如何通过代码进行修改

**Comment by CODEJAS0N** [comment]
@weichaoduo 尝试使用 Ubuntu系统部署则正常，windows部署会出现上述异常

**Comment by weichaoduo** [comment]
windows环境，下载最新版本试试

**Comment by CODEJAS0N** [comment]
> windows环境，下载最新版本试试

使用的就是官网的下载包
