### ISSUE TITLE
宝塔安装出现Access denied for user 'root'@'localhost' 

### ISSUE THREAD

**Issue by loveunique** [gopeak/masterlab#287]
这里输入对bug做出清晰简洁的描述.

**重现步骤**
1. 按照指导步骤安装
2. 登录isntall
![2020-11-25_18-04](https://user-images.githubusercontent.com/7199669/100212753-b540b680-2f48-11eb-8108-84fec81f391d.png)
3. xxxx
4. xxxxxx

**期望结果**
简洁清晰的描述期望结果

**实际结果**
简述实际看到的结果，这里可以配上截图

**附加说明**
附加或额外的信息

**Comment by weichaoduo** [comment]
访问 /install 进行图文安装

**Comment by weichaoduo** [comment]
宝塔的一键部署问题，已经在修复，需要宝塔官方审核
![图片](https://user-images.githubusercontent.com/6365163/100338838-11244180-3014-11eb-9aeb-c8b1a7c5b092.png)

**Comment by weichaoduo** [comment]
安装问题，请加QQ群314155057 并咨询群主
