### ISSUE TITLE
创建项目后，设置 ->事项设置 点击保存时sql报错

### ISSUE THREAD

**Issue by silencewul** [gopeak/masterlab#291]

**Comment by silencewul** [comment]
![image](https://user-images.githubusercontent.com/32574754/100332855-db2f8f00-300c-11eb-80fd-a8ac50f924af.png)

**Comment by weichaoduo** [comment]
bug已经在处理，很快就能修复

**Comment by silencewul** [comment]
> bug已经在处理，很快就能修复

我在字段前面加上`` ，然后语句就能成功，但是后面继续更新在project_user_role会出现重复数据

**Comment by weichaoduo** [comment]
下载此补丁包，覆盖代码即可
http://download.masterlab.vip/3.0.0RC2-3.0.0RC3-upgrade.zip
