### ISSUE TITLE
MYSQL的端口配置为其他非3306端口时，无法正常打开界面

### ISSUE THREAD

**Issue by rehot6** [gopeak/masterlab#294]
MYSQL的端口配置为其他非3306端口时，虽然安装过程没有问题，但是无法正常打开界面，会进入app/view/exception.php。
提示内容是无法连接SQL，“root@x.x.x.x”。

版本v3.0.0RC3
MYSQL使用docker安装的5.7版本，端口映射为3307。
redis和socket均没有使用。

**Comment by weichaoduo** [comment]
直接修改配置文件 config.yml 
找到 database / default / port 修改为3307

**Comment by rehot6** [comment]
谢谢解答！
