### ISSUE TITLE
文档管理无法登录

### ISSUE THREAD

**Issue by axzsd** [gopeak/masterlab#318]
提示 User/project92_100 不存在

**Comment by axzsd** [comment]
输入用户名和密码点击登录提示用户名或者密码错误

**Comment by axzsd** [comment]
![image](https://user-images.githubusercontent.com/30335866/104434121-d24b4a80-55c5-11eb-8624-ccfed6813671.png)

**Comment by axzsd** [comment]
![image](https://user-images.githubusercontent.com/30335866/104434305-0e7eab00-55c6-11eb-873f-1de89ca8bbc4.png)

**Comment by weichaoduo** [comment]
已在master分支上修复此问题，同时 要赋予php用户正在  plugin/document目录子目录读写权限

# https://github.com/gopeak/masterlab/commit/7fdb431fa0ff87208ec81edd0f350f75fa7a0a6c
