### ISSUE TITLE
协助人没法看到自己协助的事情

### ISSUE THREAD

**Issue by lakeyboy** [gopeak/masterlab#321]
事项的协助人看不到自己协助的事项

**Comment by weichaoduo** [comment]
该bug已经修复，这两天发布新版本，重新安装即可。或者现在下载master分支的代码安装

**Comment by lakeyboy** [comment]
但是只能在事项列表中查看，没发现有地方可以快速查看“自己协助且未解决的事项”，，就像“分配给我未解决的事项”这种小工具。
![image](https://user-images.githubusercontent.com/48074851/105685373-f47f8980-5f30-11eb-90a2-7d16d389e479.png)

**Comment by lakeyboy** [comment]
协助事项没办法汇总显示，

**Comment by weichaoduo** [comment]
协助人事项汇总，暂时没有此功能

**Comment by weichaoduo** [comment]
我理解你的意思了，我们将增加两个功能：
首页自定义面板增加一个：我协助的事项面板
项目里的事项列表页面增加一个预定义的过滤器：我协助的事项

**Comment by lakeyboy** [comment]
太好了，

**Comment by weichaoduo** [comment]
事项列表页面有个显示字段功能，勾中协助人，可显示协作人

**Comment by lakeyboy** [comment]
好的，已勾选
