### ISSUE TITLE
无法登录，参数错误

### ISSUE THREAD

**Issue by wenger66** [gopeak/masterlab#338]
windows10环境，无法登录，参数错误

**重现步骤**
按照http://www.masterlab.vip/help?md=install-windows-pure 教程安装，Apache启动无报错，MySQL正常，MasterLab安装完成无报错
登录显示无法登录，参数错误

**期望结果**
登录成功

**实际结果**
windows10环境
按照http://www.masterlab.vip/help?md=install-windows-pure 教程安装，Apache启动无报错，MySQL正常，MasterLab安装完成无报错

登陆，显示如下错误
![image](https://user-images.githubusercontent.com/11221205/107328089-25db8600-6ae9-11eb-9cce-3a6f38a4fdce.png)

Web请求传递参数正确，但是貌似app/ctrl/Passport.php的doLogin方法无法接收到请求参数
![image](https://user-images.githubusercontent.com/11221205/107328207-528f9d80-6ae9-11eb-96b0-42b8b93f1f1d.png)
![image](https://user-images.githubusercontent.com/11221205/107328342-88cd1d00-6ae9-11eb-9313-d0af6ae1741e.png)

var_dump(func_get_args()); 放开，打印为{}

**附加说明**
附加或额外的信息

**Comment by weichaoduo** [comment]
你这属于安装问题，具体可以联系QQ 79720699 客服给予远程协助支持。
