### ISSUE TITLE
用户列表中的“项目角色”保存成功却不生效

### ISSUE THREAD

**Issue by ZaXk** [gopeak/masterlab#353]
管理/用户管理/全部用户（列表中）/项目角色，弹出窗口编辑一用户的“所属项目角色”，随便勾选，保存，右上角提示成功，但却不生效，刷新页面再进入为修改前的状态

**重现步骤**
1. 进入 管理/用户管理/全部用户（列表中）/项目角色
2. 弹出窗口编辑一用户的“所属项目角色”
3. 随便勾选，保存
4. 刷新页面重新打开刚才编辑的用户的项目角色，可见恢复成编辑前的状态
5. 不刷新的话有缓存，能显示编辑后的状态
6. 只能通过管理/用户管理/项目角色，在具体项目角色中选择人员，才能成功编辑权限并生效

**期望结果**
保存后应能生效

**实际结果**
提示保存成功，却实际不生效。刷新页面再查看该用户的项目权限，即回到编辑前的状态。

**附加说明**

**Comment by ZaXk** [comment]
版本3.0.0RC12

**Comment by jinjiajin** [comment]
同样发现了这个问题→_→

**Comment by weichaoduo** [comment]
fixed v3.1.4
