### ISSUE TITLE
不能清空邮件队列

### ISSUE THREAD

**Issue by ZaXk** [gopeak/masterlab#354]
版本3.0.0RC12
进入系统设置/邮件队列，点击【清空全部】，报错，不能执行。【清空错误】是可以的。
报错：
Empty criteria was used, expected non-empty criteria

**重现步骤**
1. 进入系统设置/邮件队列
2. 点击【清空全部】

**期望结果**
可以清空全部邮件队列

**实际结果**
不能清空，并报错。

**附加说明**
/admin/system/emailQueueAllClear的Response status=200，但内容似乎为空。

**Comment by ZaXk** [comment]
标题写错了，应为“不能清空邮件队列”

**Comment by weichaoduo** [comment]
fixed in 3.0RC13版本
