### ISSUE TITLE
甘特图编辑事项（事项维护），“状态”永远都是“延迟处理”

### ISSUE THREAD

**Issue by ZaXk** [gopeak/masterlab#355]
从甘特图点击铅笔，编辑事项（事项维护），编辑窗口中的“状态”永远都是“延迟处理”，无法匹配到正确的值显示

**重现步骤**
1. 创建一个事项
2. 转到甘特图视图
3. 点击铅笔编辑
4. 状态显示为固定的延迟处理

**期望结果**
正确显示事项的状态值

**实际结果**
无论状态值是什么，都会显示成延迟处理

**附加说明**
此界面又不能在管理中编辑，开发又要维护多一个功能，建议使用相应类型的事项编辑界面

**Comment by ZaXk** [comment]
/dev/js/project/gantt_ajax.js
229行 $('#gantt_status').val(issue.gantt_status); -->$('#gantt_status').val(issue.status);

**Comment by weichaoduo** [comment]
感谢提出bug和修复方案
