### ISSUE TITLE
ISSUES（parent_issue）表单控件不能使用

### ISSUE THREAD

**Issue by ZaXk** [gopeak/masterlab#357]
ISSUES（parent_issue）表单控件不能使用，不能显示父事项或选择事项。

**重现步骤**
1. 创建两个事项
2. 将其一变成另一个的子事项
3. 编辑界面中添加父事项的编辑
4. 进入编辑父事项只有一个空空的输入框，没有默认值

**期望结果**
可以查看和编辑父事项，可以通过关键字检索本项目的事项

**实际结果**
父事项不显示任何内容

**附加说明**

**Comment by weichaoduo** [comment]
之前需要手动输入标题模糊查询找出父事项，现在新版本默认带出最新的50条事项
