### ISSUE TITLE
甘特图拖拽事项长度忽长忽短

### ISSUE THREAD

**Issue by ZaXk** [gopeak/masterlab#358]
甘特图拖拽事项长度忽长忽短，捉摸不透，非常诡异

**重现步骤**
1. 创建事项
2. 在甘特图视图中拖拽

**期望结果**
拖拽后，起点为拖拽的起始日期，长度=“用时”+非工作日数量，并能手动或自动保存

**实际结果**
事项长度无规则变动，不能保存更改

**附加说明**

**Comment by weichaoduo** [comment]
fixed  v3.14
