### ISSUE TITLE
事项模块中高级查询功能无法实现指定查询的功能

### ISSUE THREAD

**Issue by 18715383173** [gopeak/masterlab#372]
这里输入对bug做出清晰简洁的描述.

**重现步骤**
1. 点击侧边栏项目，进入项目中
2. 选中事项，所有事项
3. 点击高级查询按钮
4. 选择需要查询的字段，过滤结果与预期结果不符

**期望结果**
高级查询功能能够实现过滤功能

**实际结果**

**附加说明**
附加或额外的信息

**Comment by weichaoduo** [comment]
fix in v3.1.5

**Comment by weichaoduo** [comment]
patch: https://download.masterlab.vip/3.1.4-3.1.5-upgrade.zip
