### ISSUE TITLE
项目的事项界面有没有树状显示的？

### ISSUE THREAD

**Issue by fuuhoo** [gopeak/masterlab#381]
也就是每个条目的子任务可以折叠起来，这样的显示效果更可观一些。

**Comment by weichaoduo** [comment]
近期一个月内将增加此功能

**Comment by fuuhoo** [comment]
请问增加树形结构了吗

**Comment by weichaoduo** [comment]
要树形展示，目前和事项分解功能有些冲突，所以暂时未考虑在事项列表界面展示
![图片](https://user-images.githubusercontent.com/6365163/146156034-444d5134-28ee-427e-8a54-d5c30282cfd7.png)
