### ISSUE TITLE
自己新建的项目，进入甘特图页面总会一直提示“待办事项”的开始日期和接受日期未设置

### ISSUE THREAD

**Issue by E0001** [gopeak/masterlab#383]
自己新建的项目，进入甘特图页面总会一直提示“待办事项”的开始日期和接受日期未设置

![1631153292](https://user-images.githubusercontent.com/57853534/132610474-9cd8933e-2194-40f0-89f3-d6daa8dae246.jpg)

**Comment by E0001** [comment]
而且多次保存，也没有任何效果

**Comment by weichaoduo** [comment]
可以在：甘特图设置中关闭，日期检查选项
![图片](https://user-images.githubusercontent.com/6365163/146155056-45cb5ff4-fbdb-483c-a4e7-39f1ea5f60ca.png)
![图片](https://user-images.githubusercontent.com/6365163/146155107-c925d85e-1b81-435b-89d7-7c97203c4637.png)
