### ISSUE TITLE
创建事项接口api请求出错

### ISSUE THREAD

**Issue by 18715383173** [gopeak/masterlab#386]
这里输入对bug做出清晰简洁的描述.

**重现步骤**
1. 用户手册中，OpenApi文档界面
2. 在事项中创建事项内容，按照请求api和所需参数发送请求，返回状态码200，但是返回结果与预期不同

**期望结果**
与用户手册中描述的返回结果一致

**实际结果**
![image](https://user-images.githubusercontent.com/66463243/142577788-f8a686a1-0968-4d94-b08b-4da911f4df53.png)

**附加说明**
附加或额外的信息

**Comment by weichaoduo** [comment]
fixed in v3.1.8 and master
