### ISSUE TITLE
web界面无法配置用户组

### ISSUE THREAD

**Issue by LyleLaii** [gopeak/masterlab#387]
管理-用户管理界面中没有展示用户组的配置按钮，但通过url能够进入用户组配置界面。

**重现步骤**
无

**期望结果**
界面上添加配置用户组的跳转按钮

**实际结果**
界面上没有用户组按钮
![image](https://user-images.githubusercontent.com/23184705/143192633-de75714b-0db2-4c24-a44c-67d99f8d05a9.png)
通过 /admin/group uri可以访问到用户组配置界面
![image](https://user-images.githubusercontent.com/23184705/143192779-571d11d3-9332-4f90-a2f7-09396c5f28c3.png)

**附加说明**
masterlab社区版 3.1.7

**Comment by weichaoduo** [comment]
该功能无意义，只是标签功能。在新的版本中已经移除。
增加更方便的项目角色功能
![图片](https://user-images.githubusercontent.com/6365163/146172502-1f236ad9-8cfc-4bd9-974c-2b01ef715b1c.png)
