### ISSUE TITLE
模板任务的初始模块信息无法继承

### ISSUE THREAD

**Issue by 18715383173** [gopeak/masterlab#393]
这里输入对bug做出清晰简洁的描述.

**重现步骤**
1、新建模板信息如下：
![image](https://user-images.githubusercontent.com/66463243/147624464-0201d14d-3dc1-49af-bade-230a70e19b09.png)

2.基于此模板创建项目，无法继承模板项目中的初始模块信息
![image](https://user-images.githubusercontent.com/66463243/147624523-8c4f0448-27b4-441e-98e9-9567a0f7b057.png)

**期望结果**
初始化模板初始化信息能够继承

**实际结果**
简述实际看到的结果，这里可以配上截图

**附加说明**
附加或额外的信息

**Comment by weichaoduo** [comment]
fixed in v3.1.9
