### ISSUE TITLE
webhook接收不到信息

### ISSUE THREAD

**Issue by pandady** [gopeak/masterlab#400]
这里输入对bug做出清晰简洁的描述.

1 swoole 开启 

2 邮件可以正常收到
![image](https://user-images.githubusercontent.com/46336111/149475215-a53d952c-19be-442c-b2bc-fddd8f36bba7.png)

3，配置webhookurl无内容推送
![image](https://user-images.githubusercontent.com/46336111/149475378-15126bc8-2d98-482b-890d-f81d447cd230.png)

**期望结果**
按照文档描述 基于事件推送http post json=""

**Comment by pandady** [comment]
![image](https://user-images.githubusercontent.com/46336111/149476430-5eaad340-ea6d-4f0c-9eb0-75e2e7b27899.png)


![image](https://user-images.githubusercontent.com/46336111/149476511-e9ed577e-f027-413b-bf02-66c568252696.png)

补充系统配置信息

**Comment by weichaoduo** [comment]
fix in v3.3 版本
