### ISSUE TITLE
所有事项中子任务视图事项显示异常

### ISSUE THREAD

**Issue by LyleLaii** [gopeak/masterlab#415]
任务事项过多后，子任务视图无法展示所有事项

**重现步骤**
1. 创建大量事项
2. 切换至子任务视图

**期望结果**
增加分页按钮，可以查看所有事项

**实际结果**
无分页按钮，导致无法展示所有事项
<img width="1583" alt="image" src="https://user-images.githubusercontent.com/23184705/154032646-f3b55935-4801-4e6a-a55a-55f0c4e491ff.png">

**附加说明**
附加或额外的信息

**Comment by bobowsh** [comment]
我也出了类似问题，只显示出来2个事项
