### ISSUE TITLE
新加的拖动子任务视图事项功能问题

### ISSUE THREAD

**Issue by bobowsh** [gopeak/masterlab#422]
这里输入对bug做出清晰简洁的描述.

**重现步骤**
1. 拖动子任务视图的表头

**期望结果**
表头不能拖动

**实际结果**
表头能够被拖动到其他事项下。。。

**附加说明**
附加或额外的信息

**Comment by weichaoduo** [comment]
由于前端能力有限，当前版本暂时不能优化。前端重构后再解决此问题
