### ISSUE TITLE
保存搜索为项目过滤器问题

### ISSUE THREAD

**Issue by bobowsh** [gopeak/masterlab#423]
搜索保存的项目过滤器不工作

**重现步骤**
1. 搜索条件设置为类型=bug
2. 搜索后保存搜索，并勾选项目过滤器

**期望结果**
过滤器可以搜索出bug类型事项

**实际结果**
个人过滤器可以搜索出bug类型事项，项目过滤器搜索出全部类型事项，没有达到过滤效果

**附加说明**
附加或额外的信息

**Comment by weichaoduo** [comment]
请按照以下操作哦：
![图片](https://user-images.githubusercontent.com/6365163/165123589-8f68ebcb-3669-4dd6-a0b1-97faa5c89abf.png)
