### ISSUE TITLE
搜索工具栏的搜索按钮无法点击

### ISSUE THREAD

**Issue by bobowsh** [gopeak/masterlab#424]
右上角的搜索栏上的搜索图标无法点击

**重现步骤**
1. 右上角的搜索栏输入待搜索内容

**期望结果**
点击搜索图标搜索结果

**实际结果**
搜索图标无法点击

**附加说明**
附加或额外的信息

**Comment by weichaoduo** [comment]
之前需要回车搜索，新版本增加点击事件
