### ISSUE TITLE
使用webhook时，MasterlabSocke会自动被杀，导致无法进行

### ISSUE THREAD

**Issue by fxwl** [gopeak/masterlab#428]
![image](https://user-images.githubusercontent.com/26475326/156975455-366ef247-64d5-4fe7-87e9-ff4f77b303f5.png)
当有新任务需要发送通知时：
![image](https://user-images.githubusercontent.com/26475326/156975569-4c3ac773-7e92-4f3a-934d-c51fd30829b2.png)

**Comment by weichaoduo** [comment]
请改用 swoole 服务：
https://www.masterlab.vip/help?md=install-linux#%E5%85%AD%E3%80%81%E9%85%8D%E7%BD%AE%E5%BC%82%E6%AD%A5%E5%92%8C%E5%AE%9A%E6%97%B6%E7%A8%8B%E5%BA%8F
