### ISSUE TITLE
看板里，新增看板，特定数据范围—事项类型，该筛选条件无任何效果

### ISSUE THREAD

**Issue by HarveyLau1004** [gopeak/masterlab#434]
这里输入对bug做出清晰简洁的描述.

**重现步骤**
1. 打开看板
2. 新增看板
3. 特定数据范围选择事项类型，事项类型种类选择任何一项
4. 点击保存
5. 在看板里选择当前新增的看板类型，无任何数据

**期望结果**
正确显示看到的数据

**实际结果**
![image](https://user-images.githubusercontent.com/32661270/164134322-2f6f7e02-9075-4f5a-862f-d011cb943e5e.png)

**附加说明**
附加或额外的信息

**Comment by weichaoduo** [comment]
暂不能重现此bug，请加QQ79720699解决此问题
