### ISSUE TITLE
修改附件上传大小不成功

### ISSUE THREAD

**Issue by dddaddd** [gopeak/masterlab#441]
系统设置和php.ini都改了，附件超过8m的还是上传不了

**Comment by weichaoduo** [comment]
确保进行如下操作:
1. 正确找到php.ini的路径， 可通过访问 /p.php 查看 Loaded Configuration File 
如：
```
  post_max_size = 32M
  upload_max_filesize = 32M
```
  
2. 修改完要重启php服务；
3. "管理/系统设置/附件设置"修改更大的值

**Comment by dddaddd** [comment]
我是Windows系统的 改完后上传附件报
{success: false, error: "上传失败", error_code: 4, url: "", filename: "", origin_name: "", insert_id: "",…}
error
: 
"上传失败"
error_code
: 
4
filename
: 
""
insert_id
: 
""
origin_name
: 
""
success
: 
false
url
: 
""
uuid
: 
""

**Comment by dddaddd** [comment]
已解决

**Comment by cui226543** [comment]
请问这个问题是怎么修复的
