### ISSUE TITLE
这个是可以多线程的吗？

### ISSUE THREAD

**Issue by kenbankuk** [gopeak/masterlab#449]
如果部署在内网上，最多多少人可以同时使用这个平台？哪位可以回答我，谢谢了啊

**Comment by weichaoduo** [comment]
PHP 默认并不支持多线程，要使用多线程需要安装 pthread 扩展，而要安装 pthread 扩展，必须使用 --enable-maintainer-zts 参数重新编译 PHP，这个参数是指定编译 PHP 时使用线程安全方式。

不管PHP是否使用多线程，都是支持多用户同时访问的
